// Package wirepb defines the binary storage format for file and directory
// metadata. The implementation of this package is generated by the protocol
// buffer compiler.
package wirepb

//go:generate protoc --go_out=. wire.proto
