// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wire.proto

package wirepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Node is the top-level container for file and directory metadata in
// persistent storage.
type Node struct {
	Index                *Index               `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Mode                 uint32               `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	XAttrs               []*XAttr             `protobuf:"bytes,4,rep,name=x_attrs,json=xAttrs,proto3" json:"x_attrs,omitempty"`
	Children             []*Child             `protobuf:"bytes,5,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2dcdddcdf68d8e0, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIndex() *Index {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *Node) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Node) GetModTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModTime
	}
	return nil
}

func (m *Node) GetXAttrs() []*XAttr {
	if m != nil {
		return m.XAttrs
	}
	return nil
}

func (m *Node) GetChildren() []*Child {
	if m != nil {
		return m.Children
	}
	return nil
}

// An Index records the size and storage locations of file data.
type Index struct {
	TotalBytes           uint64       `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Extents              []*Extent    `protobuf:"bytes,2,rep,name=extents,proto3" json:"extents,omitempty"`
	SplitConfig          *SplitConfig `protobuf:"bytes,3,opt,name=split_config,json=splitConfig,proto3" json:"split_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2dcdddcdf68d8e0, []int{1}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetTotalBytes() uint64 {
	if m != nil {
		return m.TotalBytes
	}
	return 0
}

func (m *Index) GetExtents() []*Extent {
	if m != nil {
		return m.Extents
	}
	return nil
}

func (m *Index) GetSplitConfig() *SplitConfig {
	if m != nil {
		return m.SplitConfig
	}
	return nil
}

// An Extent describes a single contiguous span of stored data.
type Extent struct {
	Base                 uint64   `protobuf:"varint,1,opt,name=base,proto3" json:"base,omitempty"`
	Bytes                uint64   `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Blocks               []*Block `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Extent) Reset()         { *m = Extent{} }
func (m *Extent) String() string { return proto.CompactTextString(m) }
func (*Extent) ProtoMessage()    {}
func (*Extent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2dcdddcdf68d8e0, []int{2}
}

func (m *Extent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extent.Unmarshal(m, b)
}
func (m *Extent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extent.Marshal(b, m, deterministic)
}
func (m *Extent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extent.Merge(m, src)
}
func (m *Extent) XXX_Size() int {
	return xxx_messageInfo_Extent.Size(m)
}
func (m *Extent) XXX_DiscardUnknown() {
	xxx_messageInfo_Extent.DiscardUnknown(m)
}

var xxx_messageInfo_Extent proto.InternalMessageInfo

func (m *Extent) GetBase() uint64 {
	if m != nil {
		return m.Base
	}
	return 0
}

func (m *Extent) GetBytes() uint64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *Extent) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

// A Block describes the size and storage key of a data blob.
type Block struct {
	Bytes                uint64   `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2dcdddcdf68d8e0, []int{3}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetBytes() uint64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *Block) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// An XAttr records the name and value of an extended attribute.
// The contents of the value are not interpreted.
type XAttr struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XAttr) Reset()         { *m = XAttr{} }
func (m *XAttr) String() string { return proto.CompactTextString(m) }
func (*XAttr) ProtoMessage()    {}
func (*XAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2dcdddcdf68d8e0, []int{4}
}

func (m *XAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XAttr.Unmarshal(m, b)
}
func (m *XAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XAttr.Marshal(b, m, deterministic)
}
func (m *XAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XAttr.Merge(m, src)
}
func (m *XAttr) XXX_Size() int {
	return xxx_messageInfo_XAttr.Size(m)
}
func (m *XAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_XAttr.DiscardUnknown(m)
}

var xxx_messageInfo_XAttr proto.InternalMessageInfo

func (m *XAttr) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *XAttr) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// A Child records the name and storage key of a child Node.
// The name is repeated to simplify path traversal.
type Child struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Child) Reset()         { *m = Child{} }
func (m *Child) String() string { return proto.CompactTextString(m) }
func (*Child) ProtoMessage()    {}
func (*Child) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2dcdddcdf68d8e0, []int{5}
}

func (m *Child) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Child.Unmarshal(m, b)
}
func (m *Child) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Child.Marshal(b, m, deterministic)
}
func (m *Child) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Child.Merge(m, src)
}
func (m *Child) XXX_Size() int {
	return xxx_messageInfo_Child.Size(m)
}
func (m *Child) XXX_DiscardUnknown() {
	xxx_messageInfo_Child.DiscardUnknown(m)
}

var xxx_messageInfo_Child proto.InternalMessageInfo

func (m *Child) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Child) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// A SplitConfig records the block splitter preferences.
type SplitConfig struct {
	Min                  int32    `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Max                  int32    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SplitConfig) Reset()         { *m = SplitConfig{} }
func (m *SplitConfig) String() string { return proto.CompactTextString(m) }
func (*SplitConfig) ProtoMessage()    {}
func (*SplitConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2dcdddcdf68d8e0, []int{6}
}

func (m *SplitConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SplitConfig.Unmarshal(m, b)
}
func (m *SplitConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SplitConfig.Marshal(b, m, deterministic)
}
func (m *SplitConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitConfig.Merge(m, src)
}
func (m *SplitConfig) XXX_Size() int {
	return xxx_messageInfo_SplitConfig.Size(m)
}
func (m *SplitConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SplitConfig proto.InternalMessageInfo

func (m *SplitConfig) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *SplitConfig) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SplitConfig) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func init() {
	proto.RegisterType((*Node)(nil), "wirepb.Node")
	proto.RegisterType((*Index)(nil), "wirepb.Index")
	proto.RegisterType((*Extent)(nil), "wirepb.Extent")
	proto.RegisterType((*Block)(nil), "wirepb.Block")
	proto.RegisterType((*XAttr)(nil), "wirepb.XAttr")
	proto.RegisterType((*Child)(nil), "wirepb.Child")
	proto.RegisterType((*SplitConfig)(nil), "wirepb.SplitConfig")
}

func init() { proto.RegisterFile("wire.proto", fileDescriptor_f2dcdddcdf68d8e0) }

var fileDescriptor_f2dcdddcdf68d8e0 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0x9a, 0x38, 0x5d, 0x26, 0xbb, 0x08, 0x19, 0x0e, 0xd1, 0x5e, 0xb6, 0x0a, 0x02, 0x95,
	0x03, 0xa9, 0x00, 0xc1, 0x9d, 0x5d, 0xed, 0x81, 0x0b, 0x07, 0xc3, 0x01, 0x4e, 0x91, 0xd3, 0xb8,
	0xc5, 0x6a, 0x12, 0x47, 0xb1, 0x0b, 0x29, 0x9f, 0xc0, 0x9f, 0xf1, 0x57, 0x68, 0xc6, 0x09, 0x6d,
	0x05, 0xa7, 0xbc, 0x79, 0xf3, 0xe6, 0xbd, 0xf1, 0x28, 0x00, 0x3f, 0x74, 0xaf, 0xf2, 0xae, 0x37,
	0xce, 0xf0, 0x18, 0x71, 0x57, 0x5e, 0xdf, 0x6c, 0x8d, 0xd9, 0xd6, 0x6a, 0x45, 0x6c, 0xb9, 0xdf,
	0xac, 0x9c, 0x6e, 0x94, 0x75, 0xb2, 0xe9, 0xbc, 0x30, 0xfb, 0x1d, 0x40, 0xf4, 0xd1, 0x54, 0x8a,
	0x3f, 0x05, 0xa6, 0xdb, 0x4a, 0x0d, 0x69, 0xb0, 0x08, 0x96, 0xc9, 0xeb, 0xab, 0xdc, 0x3b, 0xe4,
	0x1f, 0x90, 0x14, 0xbe, 0xc7, 0x39, 0x44, 0x8d, 0xa9, 0x54, 0x3a, 0x5b, 0x04, 0xcb, 0x2b, 0x41,
	0x98, 0xbf, 0x85, 0x8b, 0xc6, 0x54, 0x05, 0x1a, 0xa7, 0x21, 0xcd, 0x5e, 0xe7, 0x3e, 0x35, 0x9f,
	0x52, 0xf3, 0xcf, 0x53, 0xaa, 0x98, 0x37, 0xa6, 0xc2, 0x8a, 0x3f, 0x87, 0xf9, 0x50, 0x48, 0xe7,
	0x7a, 0x9b, 0x46, 0x8b, 0xf0, 0x34, 0xf1, 0xcb, 0x7b, 0xe7, 0x7a, 0x11, 0x0f, 0xf8, 0xb1, 0xfc,
	0x05, 0x5c, 0xac, 0xbf, 0xe9, 0xba, 0xea, 0x55, 0x9b, 0xb2, 0x73, 0xe1, 0x1d, 0xf2, 0xe2, 0x6f,
	0x3b, 0xfb, 0x15, 0x00, 0xa3, 0x75, 0xf9, 0x0d, 0x24, 0xce, 0x38, 0x59, 0x17, 0xe5, 0xc1, 0x29,
	0x4b, 0x4f, 0x8a, 0x04, 0x10, 0x75, 0x8b, 0x0c, 0x5f, 0xc2, 0x5c, 0x0d, 0x4e, 0xb5, 0xce, 0xa6,
	0x33, 0x32, 0x7d, 0x38, 0x99, 0xde, 0x13, 0x2d, 0xa6, 0x36, 0x7f, 0x07, 0x97, 0xb6, 0xab, 0xb5,
	0x2b, 0xd6, 0xa6, 0xdd, 0xe8, 0xed, 0xf8, 0xc4, 0xc7, 0x93, 0xfc, 0x13, 0xf6, 0xee, 0xa8, 0x25,
	0x12, 0x7b, 0x2c, 0xb2, 0xaf, 0x10, 0x7b, 0x2b, 0x3c, 0x5a, 0x29, 0xad, 0x1a, 0xb7, 0x20, 0xcc,
	0x9f, 0x00, 0xf3, 0xab, 0xcd, 0x88, 0xf4, 0x05, 0x7f, 0x06, 0x71, 0x59, 0x9b, 0xf5, 0xce, 0xa6,
	0xe1, 0xf9, 0x4b, 0x6f, 0x91, 0x15, 0x63, 0x33, 0x5b, 0x01, 0x23, 0xe2, 0xe8, 0x12, 0x9c, 0xba,
	0x3c, 0x82, 0x70, 0xa7, 0x0e, 0xe4, 0x7c, 0x29, 0x10, 0x66, 0xaf, 0x80, 0xd1, 0x51, 0x71, 0x95,
	0x56, 0x36, 0x7e, 0x95, 0x07, 0x82, 0x30, 0x9a, 0x7c, 0x97, 0xf5, 0x5e, 0x8d, 0x03, 0xbe, 0xc8,
	0x5e, 0x02, 0xa3, 0xf3, 0xfe, 0x77, 0xe4, 0xdf, 0x84, 0x7b, 0x48, 0x4e, 0x2e, 0x81, 0x82, 0x46,
	0xb7, 0x34, 0xc3, 0x04, 0x42, 0xb4, 0xb1, 0xfa, 0xa7, 0x0f, 0x61, 0x82, 0x30, 0xa9, 0xe4, 0x40,
	0x17, 0x45, 0x95, 0x1c, 0xca, 0x98, 0xfe, 0x98, 0x37, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xab,
	0x50, 0xd6, 0x21, 0xcb, 0x02, 0x00, 0x00,
}
