// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encrypted.proto

package encpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Encrypted is the storage format for an encrypted blob.
type Encrypted struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Init                 []byte   `protobuf:"bytes,2,opt,name=init,proto3" json:"init,omitempty"`
	UncompressedSize     int64    `protobuf:"varint,3,opt,name=uncompressed_size,json=uncompressedSize,proto3" json:"uncompressed_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Encrypted) Reset()         { *m = Encrypted{} }
func (m *Encrypted) String() string { return proto.CompactTextString(m) }
func (*Encrypted) ProtoMessage()    {}
func (*Encrypted) Descriptor() ([]byte, []int) {
	return fileDescriptor_0acd50b6c00e1db6, []int{0}
}

func (m *Encrypted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Encrypted.Unmarshal(m, b)
}
func (m *Encrypted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Encrypted.Marshal(b, m, deterministic)
}
func (m *Encrypted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Encrypted.Merge(m, src)
}
func (m *Encrypted) XXX_Size() int {
	return xxx_messageInfo_Encrypted.Size(m)
}
func (m *Encrypted) XXX_DiscardUnknown() {
	xxx_messageInfo_Encrypted.DiscardUnknown(m)
}

var xxx_messageInfo_Encrypted proto.InternalMessageInfo

func (m *Encrypted) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Encrypted) GetInit() []byte {
	if m != nil {
		return m.Init
	}
	return nil
}

func (m *Encrypted) GetUncompressedSize() int64 {
	if m != nil {
		return m.UncompressedSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Encrypted)(nil), "encpb.Encrypted")
}

func init() { proto.RegisterFile("encrypted.proto", fileDescriptor_0acd50b6c00e1db6) }

var fileDescriptor_0acd50b6c00e1db6 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcd, 0x4b, 0x2e,
	0xaa, 0x2c, 0x28, 0x49, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0xcd, 0x4b,
	0x2e, 0x48, 0x52, 0x4a, 0xe0, 0xe2, 0x74, 0x85, 0xc9, 0x08, 0x09, 0x71, 0xb1, 0xa4, 0x24, 0x96,
	0x24, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0xd9, 0x20, 0xb1, 0xcc, 0xbc, 0xcc, 0x12,
	0x09, 0x26, 0x88, 0x18, 0x88, 0x2d, 0xa4, 0xcd, 0x25, 0x58, 0x9a, 0x97, 0x9c, 0x9f, 0x5b, 0x50,
	0x94, 0x5a, 0x5c, 0x9c, 0x9a, 0x12, 0x5f, 0x9c, 0x59, 0x95, 0x2a, 0xc1, 0xac, 0xc0, 0xa8, 0xc1,
	0x1c, 0x24, 0x80, 0x2c, 0x11, 0x9c, 0x59, 0x95, 0x9a, 0xc4, 0x06, 0xb6, 0xcf, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xc3, 0x92, 0x6e, 0x5d, 0x82, 0x00, 0x00, 0x00,
}
